apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tzb5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-tzb5@sha256:cd47dfa1bea1e3d2cdb33b55a7a5b7bdaf11793058fd782d52a26ebaebf40e04
        name: my-nodejs
        resources: {}
status: {}
